name: Run Ansible Playbook

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infraestructure/configuration/**'
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: challenge

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "jackt72xp@gmail.com"
        git config --global user.name "Jack Torpoco"


    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i ./infraestructure/configuration/hosts.ini ./infraestructure/configuration/setup.yml -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"' -e ansible_become_pass="${{ secrets.ANSIBLE_SUDO_PASS }}"
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    - name: Commit files
      run: |
        git add .
        git commit -m "Update configuration files via Ansible"

    - name: Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Bifrost3-0/challenge-am.git
        git push


    - name: Clean up
      if: always()
      run: echo "Clean up actions if necessary"
