name: Run Ansible Playbook

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infraestructure/configuration/**'
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook (assuming secrets manager is used)
      run: ansible-playbook -i ./infraestructure/configuration/hosts.ini ./infraestructure/configuration/setup.yml -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}


    - name: Clean up
      if: always()
      run: echo "Clean up actions if necessary"
